packages:
  - apps/*
  - configs/*
  - packages/*

catalog:
  eslint: ^9.18.0
  tailwindcss: ^3.4.17
  turbo: ^2.3.3
  typescript: ^5.7.2
  prettier: ^3.4.2

catalogs:
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19.0.7
    "@types/react-dom": ^19.0.3
